# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-16 06:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('body', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('upvotes', models.IntegerField(default=0)),
                ('num_votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerComment',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('body', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('answer', 
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='website.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('answer',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='website.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='FossCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('qid', models.IntegerField()),
                ('aid', models.IntegerField(default=0)),
                ('cid', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('confirmation_code', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('address', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models
                                                           .deletion.CASCADE,
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=1)),
                ('num_votes', models.IntegerField(default=0)),
                ('category',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='website.FossCategory')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to=settings.AUTH_USER_MODEL)),
                ('userDownVotes',
                 models.ManyToManyField(blank=True,
                                        related_name='postDownVotes',
                                        to=settings.AUTH_USER_MODEL)),
                ('userUpVotes',
                 models.ManyToManyField(blank=True,
                 related_name='postUpVotes',
                 to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'date_created',
            },
        ),
        migrations.CreateModel(
            name='QuestionComment',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('body', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('question',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='website.Question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionVote',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('question',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='website.Question')),
            ],
        ),
        migrations.CreateModel(
            name='SubFossCategory',
            fields=[
                ('id',
                 models.AutoField(auto_created=True, primary_key=True,
                                  serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('parent', 
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='website.FossCategory')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='website.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='userDownVotes',
            field=models.ManyToManyField(blank=True,
                                         related_name='postAnswerDownVotes',
                                         to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='userUpVotes',
            field=models.ManyToManyField(blank=True,
                                         related_name='postAnswerUpVotes',
                                         to=settings.AUTH_USER_MODEL),
        ),
    ]
