# Generated by Django 2.1.3 on 2018-11-18 06:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answercomment',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
