# Generated by Django 2.0.6 on 2018-06-13 05:53

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20180612_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questioncomment',
            name='question',
        ),
        migrations.AlterField(
            model_name='answer',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=0, size=[800, 800], upload_to='images/answers/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=0, size=[800, 800], upload_to='images/questions/'),
        ),
        migrations.DeleteModel(
            name='QuestionComment',
        ),
    ]
