# Generated by Django 2.1.3 on 2018-11-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20181118_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answercomment',
            name='body',
            field=models.TextField(),
        ),
    ]
