# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-23 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_fosscategory_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fosscategory',
            old_name='tag',
            new_name='default_tags',
        ),
    ]
