# Generated by Django 2.0.6 on 2018-06-27 11:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_answer_upvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
