# Generated by Django 2.1.3 on 2018-11-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_advertisebanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisebanner',
            name='body',
            field=models.TextField(default='Null'),
        ),
    ]
