# Generated by Django 2.1.3 on 2019-06-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20190612_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='sub_category',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
