# Generated by Django 2.1.3 on 2019-06-26 10:42

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20190612_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='fosscategory',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=0, size=[800, 800], upload_to='images/fossCategory/'),
        ),
    ]
