# Generated by Django 2.2.7 on 2022-08-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_fosscategory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduled_Auto_Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_sent_date', models.CharField(max_length=255)),
                ('is_sent', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='is_answering_closed',
            field=models.BooleanField(default=False),
        ),
    ]
